name: Build Spotty for Linux

on: [workflow_dispatch]

env:
  CARGO_TERM_COLOR: always
  KEYMASTER_CLIENT_ID: ${{ secrets.KEYMASTER_CLIENT_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Write Build Configuration File
      uses: DamianReeves/write-file-action@v1.0
      with:
        path: ./src/client_id.txt
        contents: ${{ env.KEYMASTER_CLIENT_ID }}
        write-mode: overwrite

    - name: Build
      run: ./xbuild.sh

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: spotty-linux
        path: target/**/spotty