name: Build Spotty for Windows

on: [workflow_dispatch]

env:
  CARGO_TERM_COLOR: always
  KEYMASTER_CLIENT_ID: ${{ secrets.KEYMASTER_CLIENT_ID }}

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - uses: DamianReeves/write-file-action@v1.0
      with:
        path: ./src/client_id.txt
        contents: ${{ env.KEYMASTER_CLIENT_ID }}
        write-mode: overwrite

    - name: Build
      run: cargo build --release

    - uses: actions/upload-artifact@v2
      with:
        name: spotty.exe
        path: target/release/spotty.exe